#!/bin/sh
# xrandr --output eDP --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-1-0 --off --output DP-1-1 --off --output HDMI-1-0 --off --output DP-1-2 --off
kscreen-doctor output.eDP-1.enable output.eDP-1.mode.0 output.HDMI-A-1.disable
