#!/bin/sh

kscreen-doctor output.eDP-1.enable output.eDP-1.mode.2 output.eDP-1.position.0,313 \
               output.HDMI-A-1.enable output.HDMI-A-1.mode.25 output.HDMI-A-1.position.2227,0

sleep 3

kscreen-doctor output.eDP-1.enable output.eDP-1.mode.1 output.HDMI-A-1.disable

sleep 3

kscreen-doctor output.eDP-1.enable output.eDP-1.mode.2 output.eDP-1.position.0,313 \
               output.HDMI-A-1.enable output.HDMI-A-1.mode.25 output.HDMI-A-1.position.2227,0
