#!/bin/sh
# xrandr --output eDP --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-1-0 --off --output DP-1-1 --off --output HDMI-1-0 --mode 2560x1440 --pos 2560x0 --rotate normal --output DP-1-2 --off
# sleep 5
# xrandr --output eDP --primary --mode 2560x1440 --pos 0x360 --rotate normal --output DP-1-0 --off --output DP-1-1 --off --output HDMI-1-0 --mode 3840x2160 --pos 2560x0 --rotate normal --output DP-1-2 --off

kscreen-doctor output.eDP-1.enable output.eDP-1.mode.2 output.eDP-1.position.0,313 \
               output.HDMI-A-1.enable output.HDMI-A-1.mode.24 output.HDMI-A-1.position.2227,0

sleep 3

kscreen-doctor output.eDP-1.enable output.eDP-1.mode.1 output.HDMI-A-1.disable

sleep 3

kscreen-doctor output.eDP-1.enable output.eDP-1.mode.2 output.eDP-1.position.0,313 \
               output.HDMI-A-1.enable output.HDMI-A-1.mode.24 output.HDMI-A-1.position.2227,0
