#!/bin/sh

kscreen-doctor output.eDP-2.enable output.eDP-2.mode.2 output.eDP-2.position.0,203 \
               output.HDMI-A-1.enable output.HDMI-A-1.mode.25 output.HDMI-A-1.position.2134,0

sleep 3

kscreen-doctor output.eDP-2.enable output.eDP-2.mode.1 output.HDMI-A-1.disable

sleep 3

kscreen-doctor output.eDP-2.enable output.eDP-2.mode.2 output.eDP-2.position.0,203 \
               output.HDMI-A-1.enable output.HDMI-A-1.mode.25 output.HDMI-A-1.position.2134,0
