
theme = "gruvbox"

[editor]
line-number = "relative"
idle-timeout = 200
true-color = true
completion-trigger-len = 2

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[keys.normal]
C-b = "goto_line_start"
C-a = "goto_line_start"
C-e = "goto_line_end"
"space" = { l = "jump_view_right", h = "jump_view_left", k = "jump_view_up", j = "jump_view_down" }
